[package]
name = "vpassword-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.145"
tokio = {version = "1.48.0", features = ["full"]}
vpassword-core = { path = "../vpassword-core" }
zeroize = "1.8.2"
