[package]
name = "vpassword-client"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
passwords = "3.1.16"
clap = { version = "4.5.51", features = ["derive"] }
ratatui = { version = "0.29.0", features = ["all-widgets"] }
crossterm = "0.29.0"
color-eyre = "0.6.5"
vpassword-core = { path = "../vpassword-core" }
serde_json = "1.0.105"
tokio = {version = "1.48.0", features = ["full"]}
